[versions]
agp = "8.8.2"
xposed = "82"
dexkit = "2.0.3"
kotlin = "2.1.10"

[libraries]
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

